name: Mi First Workflow

on: [Push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Imprimir Message
        run: |
          echo "Hola OS Enterprise"

    
