name: Variables de Org

on: 
  workflow_dispatch
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Leer Vars
        run: |
          echo "Entorno (vars) = ${{ vars.ENTORNO }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Leer Vars
        run: |
          echo "Entorno (vars) = ${{ vars.ENTORNO }}"
